version: '3'

services:
  be:
    build: .
    container_name: TODO-v2-BE
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    build:
      context: ./mysql
    container_name: TODO-V2-DB
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sergey
      MYSQL_DATABASE: nicolas-db
      MYSQL_USER: sergey
      MYSQL_PASSWORD: sergey
