# Generated by Django 4.2.7 on 2023-12-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_alter_todoitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
