# Generated by Django 4.2.7 on 2023-12-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
