# Generated by Django 4.2.7 on 2023-12-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
